#ifndef PHASE2_PALETTES_H
#define PHASE2_PALETTES_H

#include <FastLED.h>

extern CRGBPalette256 Palettes[11];
DECLARE_GRADIENT_PALETTE(C0);
DECLARE_GRADIENT_PALETTE(C1);
DECLARE_GRADIENT_PALETTE(C2);
DECLARE_GRADIENT_PALETTE(C3);
DECLARE_GRADIENT_PALETTE(C4);
DECLARE_GRADIENT_PALETTE(C5);
DECLARE_GRADIENT_PALETTE(C6);
DECLARE_GRADIENT_PALETTE(C7);
DECLARE_GRADIENT_PALETTE(C8);
DECLARE_GRADIENT_PALETTE(C9);
DECLARE_GRADIENT_PALETTE(C10);

#endif
